"""Add scheduling fields to custom agents

Revision ID: 69ae6eb9bbfb
Revises: 24cb5d6079b4
Create Date: 2026-02-18 18:16:25.698178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '69ae6eb9bbfb'
down_revision = '24cb5d6079b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_analytics_agent_date', table_name='agent_analytics')
    op.drop_index('idx_agent_analytics_user_date', table_name='agent_analytics')
    op.drop_table('agent_analytics')
    op.drop_index('idx_tool_usage_agent', table_name='tool_usage_logs')
    op.drop_index('idx_tool_usage_timestamp', table_name='tool_usage_logs')
    op.drop_table('tool_usage_logs')
    op.drop_index('ix_agent_conversations_agent_id', table_name='agent_conversations')
    op.drop_index('ix_agent_conversations_user_id', table_name='agent_conversations')
    op.drop_index('ix_agent_knowledge_files_agent_id', table_name='agent_knowledge_files')
    op.drop_index('ix_agent_messages_conversation_id', table_name='agent_messages')
    op.add_column('custom_agents', sa.Column('trigger', sa.String(length=20), server_default='manual', nullable=False))
    op.add_column('custom_agents', sa.Column('schedule', sa.String(length=100), nullable=True))
    op.add_column('custom_agents', sa.Column('schedule_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('custom_agents', sa.Column('last_scheduled_run', sa.DateTime(), nullable=True))
    op.add_column('custom_agents', sa.Column('next_scheduled_run', sa.DateTime(), nullable=True))
    op.drop_index('ix_custom_agents_category', table_name='custom_agents')
    op.drop_index('ix_custom_agents_team_id', table_name='custom_agents')
    op.drop_index('ix_custom_agents_user_id', table_name='custom_agents')
    op.drop_index('ix_custom_agents_visibility', table_name='custom_agents')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_index('ix_team_members_user_id', table_name='team_members')
    op.drop_constraint('uq_team_members_team_user', 'team_members', type_='unique')
    op.drop_index('ix_teams_created_by', table_name='teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_teams_created_by', 'teams', ['created_by'], unique=False)
    op.create_unique_constraint('uq_team_members_team_user', 'team_members', ['team_id', 'user_id'])
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('ix_custom_agents_visibility', 'custom_agents', ['visibility'], unique=False)
    op.create_index('ix_custom_agents_user_id', 'custom_agents', ['user_id'], unique=False)
    op.create_index('ix_custom_agents_team_id', 'custom_agents', ['team_id'], unique=False)
    op.create_index('ix_custom_agents_category', 'custom_agents', ['category'], unique=False)
    op.drop_column('custom_agents', 'next_scheduled_run')
    op.drop_column('custom_agents', 'last_scheduled_run')
    op.drop_column('custom_agents', 'schedule_enabled')
    op.drop_column('custom_agents', 'schedule')
    op.drop_column('custom_agents', 'trigger')
    op.create_index('ix_agent_messages_conversation_id', 'agent_messages', ['conversation_id'], unique=False)
    op.create_index('ix_agent_knowledge_files_agent_id', 'agent_knowledge_files', ['agent_id'], unique=False)
    op.create_index('ix_agent_conversations_user_id', 'agent_conversations', ['user_id'], unique=False)
    op.create_index('ix_agent_conversations_agent_id', 'agent_conversations', ['agent_id'], unique=False)
    op.create_table('tool_usage_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], name='tool_usage_logs_agent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tool_usage_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tool_usage_logs_pkey')
    )
    op.create_index('idx_tool_usage_timestamp', 'tool_usage_logs', ['timestamp'], unique=False)
    op.create_index('idx_tool_usage_agent', 'tool_usage_logs', ['agent_id'], unique=False)
    op.create_table('agent_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_runs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('successful_runs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failed_runs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('avg_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_response_time', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tool_calls_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], name='agent_analytics_agent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agent_analytics_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_analytics_pkey')
    )
    op.create_index('idx_agent_analytics_user_date', 'agent_analytics', ['user_id', 'date'], unique=False)
    op.create_index('idx_agent_analytics_agent_date', 'agent_analytics', ['agent_id', 'date'], unique=False)
    # ### end Alembic commands ###
